name = "SpectrometerControl"
uuid = "b7f148f4-bcdf-11e9-12fa-b7010a33870d"
authors = ["Connor Hayward <connor.hayward@hotmail.co.uk>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
